// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace JakeTest
{
    
    #region Windows Form Designer generated code
    public partial class EastingNorthingDialog
    {
        private void InitializeComponent()
        {
            this.label_Easting = new System.Windows.Forms.Label();
            this.label_Northing = new System.Windows.Forms.Label();
            this.text_Easting = new System.Windows.Forms.TextBox();
            this.text_Northing = new System.Windows.Forms.TextBox();
            this.button_OK = new System.Windows.Forms.Button();
            this.button_Cancel = new System.Windows.Forms.Button();
            // 
            // label_Easting
            // 
            this.label_Easting.Name = "label_Easting";
            this.label_Easting.Location = new System.Drawing.Point(16, 16);
            this.label_Easting.Image = null;
            this.label_Easting.TabIndex = 0;
            this.label_Easting.Size = new System.Drawing.Size(56, 20);
            this.label_Easting.Text = "Easting:";
            // 
            // label_Northing
            // 
            this.label_Northing.Name = "label_Northing";
            this.label_Northing.Location = new System.Drawing.Point(16, 36);
            this.label_Northing.Image = null;
            this.label_Northing.TabIndex = 0;
            this.label_Northing.Size = new System.Drawing.Size(56, 20);
            this.label_Northing.Text = "Northing:";
            // 
            // text_Easting
            // 
            this.text_Easting.Name = "text_Easting";
            this.text_Easting.ForeColor = System.Drawing.SystemColors.WindowText;
            this.text_Easting.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.text_Easting.Location = new System.Drawing.Point(80, 16);
            this.text_Easting.TabIndex = 1;
            this.text_Easting.Size = new System.Drawing.Size(96, 20);
            this.text_Easting.BackColor = System.Drawing.SystemColors.Window;
            this.text_Easting.Text = "";
            // 
            // text_Northing
            // 
            this.text_Northing.Name = "text_Northing";
            this.text_Northing.ForeColor = System.Drawing.SystemColors.WindowText;
            this.text_Northing.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.text_Northing.Location = new System.Drawing.Point(80, 36);
            this.text_Northing.TabIndex = 1;
            this.text_Northing.Size = new System.Drawing.Size(96, 20);
            this.text_Northing.BackColor = System.Drawing.SystemColors.Window;
            this.text_Northing.Text = "";
            // 
            // button_OK
            // 
            this.button_OK.Name = "button_OK";
            this.button_OK.Location = new System.Drawing.Point(36, 64);
            this.button_OK.TabIndex = 2;
            this.button_OK.Size = new System.Drawing.Size(64, 20);
            this.button_OK.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.button_OK.Text = "OK";
            this.button_OK.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.button_OK.UseVisualStyleBackColor = true;
            // 
            // button_Cancel
            // 
            this.button_Cancel.Name = "button_Cancel";
            this.button_Cancel.Location = new System.Drawing.Point(112, 64);
            this.button_Cancel.TabIndex = 3;
            this.button_Cancel.Size = new System.Drawing.Size(64, 20);
            this.button_Cancel.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.button_Cancel.Text = "Cancel";
            this.button_Cancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.button_Cancel.UseVisualStyleBackColor = true;
            // 
            // EastingNorthingDialog
            // 
            this.Name = "EastingNorthingDialog";
            this.MinimizeBox = false;
            this.MaximizeBox = false;
            this.TopMost = true;
            this.ClientSize = new System.Drawing.Size(204, 90);
            this.Controls.Add(this.label_Easting);
            this.Controls.Add(this.label_Northing);
            this.Controls.Add(this.text_Easting);
            this.Controls.Add(this.text_Northing);
            this.Controls.Add(this.button_OK);
            this.Controls.Add(this.button_Cancel);
            this.CancelButton = this.button_Cancel;
            this.Text = "Enter East & North";
            this.AcceptButton = this.button_OK;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
        }
        private System.Windows.Forms.Label label_Easting;
        private System.Windows.Forms.Label label_Northing;
        private System.Windows.Forms.TextBox text_Easting;
        private System.Windows.Forms.TextBox text_Northing;
        private System.Windows.Forms.Button button_OK;
        private System.Windows.Forms.Button button_Cancel;
    }
    #endregion
}
