// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SamMapTool
{
    
    #region Windows Form Designer generated code
    public partial class HelpDialog
    {
        private void InitializeComponent()
        {
            this.richTextBox1 = new System.Windows.Forms.RichTextBox();
            this.button_OK = new System.Windows.Forms.Button();
            // 
            // richTextBox1
            // 
            this.richTextBox1.Name = "richTextBox1";
            this.richTextBox1.ForeColor = System.Drawing.SystemColors.WindowText;
            this.richTextBox1.ZoomFactor = 1F;
            this.richTextBox1.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.richTextBox1.Location = new System.Drawing.Point(16, 24);
            this.richTextBox1.TabIndex = 0;
            this.richTextBox1.Size = new System.Drawing.Size(512, 392);
            this.richTextBox1.BackColor = System.Drawing.SystemColors.Window;
            this.richTextBox1.Text = "richTextBox1";
            // 
            // button_OK
            // 
            this.button_OK.Name = "button_OK";
            this.button_OK.Location = new System.Drawing.Point(240, 432);
            this.button_OK.TabIndex = 1;
            this.button_OK.Size = new System.Drawing.Size(60, 36);
            this.button_OK.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.button_OK.Text = "OK";
            this.button_OK.UseVisualStyleBackColor = true;
            this.button_OK.Click += new System.EventHandler(this.button_OK_Click);
            // 
            // HelpDialog
            // 
            this.Name = "HelpDialog";
            this.ClientSize = new System.Drawing.Size(545, 476);
            this.Controls.Add(this.richTextBox1);
            this.Controls.Add(this.button_OK);
            this.Text = "HelpDialog";
            this.AcceptButton = this.button_OK;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            this.Load += new System.EventHandler(this.onLoad);
        }
        private System.Windows.Forms.RichTextBox richTextBox1;
        private System.Windows.Forms.Button button_OK;
    }
    #endregion
}
