// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace JakeTest
{
    
    #region Windows Form Designer generated code
    public partial class JakeTestMain
    {
        private void InitializeComponent()
        {
            this.panel1 = new System.Windows.Forms.Panel();
            this.button1 = new System.Windows.Forms.Button();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.textBox1 = new System.Windows.Forms.TextBox();
            this.button2 = new System.Windows.Forms.Button();
            this.panel1.SuspendLayout();
            // 
            // panel1
            // 
            this.panel1.Name = "panel1";
            this.panel1.Location = new System.Drawing.Point(16, 24);
            this.panel1.TabIndex = 0;
            this.panel1.Controls.Add(this.button1);
            this.panel1.Controls.Add(this.button2);
            this.panel1.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.panel1.Size = new System.Drawing.Size(520, 48);
            this.panel1.BackColor = System.Drawing.SystemColors.ControlDark;
            this.panel1.Text = "panel1";
            // 
            // button1
            // 
            this.button1.Name = "button1";
            this.button1.Location = new System.Drawing.Point(8, 12);
            this.button1.TabIndex = 0;
            this.button1.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.button1.BackColor = System.Drawing.SystemColors.ControlDark;
            this.button1.Text = "Quit";
            this.button1.UseVisualStyleBackColor = true;
            // 
            // pictureBox1
            // 
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Location = new System.Drawing.Point(16, 80);
            this.pictureBox1.Image = null;
            this.pictureBox1.TabIndex = 0;
            this.pictureBox1.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.pictureBox1.Size = new System.Drawing.Size(512, 512);
            this.pictureBox1.BackColor = System.Drawing.SystemColors.ControlDarkDark;
            this.pictureBox1.Text = "pictureBox1";
            // 
            // textBox1
            // 
            this.textBox1.Name = "textBox1";
            this.textBox1.ForeColor = System.Drawing.SystemColors.WindowText;
            this.textBox1.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textBox1.Location = new System.Drawing.Point(24, 608);
            this.textBox1.TabIndex = 1;
            this.textBox1.Size = new System.Drawing.Size(504, 20);
            this.textBox1.BackColor = System.Drawing.SystemColors.Window;
            this.textBox1.Text = "";
            // 
            // button2
            // 
            this.button2.Name = "button2";
            this.button2.Location = new System.Drawing.Point(96, 12);
            this.button2.TabIndex = 0;
            this.button2.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.button2.BackColor = System.Drawing.SystemColors.ControlDark;
            this.button2.Text = "Load Image";
            this.button2.UseVisualStyleBackColor = true;
            // 
            // JakeTestMain
            // 
            this.Name = "JakeTestMain";
            this.ClientSize = new System.Drawing.Size(552, 645);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.pictureBox1);
            this.Controls.Add(this.textBox1);
            this.Text = "JakeTestMain_Jake";
            this.panel1.ResumeLayout(false);
        }
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Button button1;
        private System.Windows.Forms.PictureBox pictureBox1;
        private System.Windows.Forms.TextBox textBox1;
        private System.Windows.Forms.Button button2;
    }
    #endregion
}
